server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: consumer-service
feign:
  hystrix:
    enabled: true
