server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.188.88:3306/springboot-test?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
  application:
    name: user-service

user:
  time: jj
